const translateData = {
  底板: 'Tấm Đáy',
  顶板: 'Tấm Đỉnh',
  踢脚板: 'Chân',
  踢脚加固条: 'Chân Phụ',
  三合一固定层板: 'Đợt Ngang',
  活动层板: 'Đợt Di Động',
  空白层板: 'Đợt không liên kết',
  二合一半固定层板: 'Đợt Cam',
  螺钉通孔二合一固定层板: 'Đợt lk vít',
  左侧板: 'Hồi Trái',
  右侧板: 'Hồi Phải',
  空白中立板: 'Hồi không lk',
  普通抽屉前板: 'Ngăn kéo trước',
  中立板: 'Hồi Giữa',
  后板: 'Ngăn kéo sau',
  普通抽屉后板: 'Ngăn kéo sau',
  左侧帮: 'Ngăn kéo trái',
  普通抽屉左侧帮: 'Ngăn kéo trái',
  右侧帮: 'Ngăn kéo phải',
  普通抽屉右侧帮: 'Ngăn kéo phải',
  普通抽屉抽屉底板: 'Đáy ngăn kéo',
  衣通管杆: 'Suốt áo',
  衣通两端支撑件: 'Bát treo suốt',
  半盖式: 'BL 1/2',
  内嵌式: 'BL 0',
  格架横板: 'Rượu dọc',
  格架竖板: 'Rượu ngang',
  面板: 'Mặt ngăn kéo',
  普通抽屉吸塑面板: 'Mặt ngăn kéo',
  背板: 'Tấm Hậu',
  纵向拉条: 'Nối hậu',
  前板: 'Cánh giả',
  顶挡侧板: 'Kẹp phào',
  顶挡板: 'Phào',
  三节滑轨: 'Ray bi',
  辅板: 'Thêm',
  竖拉条: 'Xà đứng',
  平拉条: 'Xà ngang',
  Cua: 'Cánh cửa',
  门板: 'Cánh cửa',
  铰链: 'Bản lề',
  三合一连接件: 'Lỗ cam',
  圆木榫: 'Chốt gỗ',
  拉手: 'Tay nắm',
  滑轨: 'Ray bi',
  全盖式: 'BL 1',
  裤架: 'Gía treo quần',
  镀镍: 'Mạ niken',
  木质: 'Gỗ',
  '厚1 | 薄0': 'Dày 1/Mỏng0',
  三薄一厚: 'Ba mỏng - 1 dày',
  否: 'Không',
  是: 'Có',
  二长: '2 dài',
  一长二短: '1 dài và 2 ngắn',
  四边: '4 cạnh',
  无: '0',
  二短: '2 ngắn',
  二长一短: '2 dài 1 ngắn',
  一长一短: '1 dài 1 ngắn',
  一长: '1 dài',
  一短: '1 ngắn',
  孔塞: 'Chốt đợt di động',
  用户自定义安装样式: 'Theo chỉ định'
}

export default translateData
