export default {
    '底板': 'Tấm Đáy',
    '顶板': 'Tấm Đỉnh',
    '踢脚板': 'Chân',
    '踢脚加固条': 'Chân Phụ',
    '三合一固定层板': 'Đợt Ngang',
    '活动层板': 'Đợt Di Động',
    '空白层板': 'Đợt không liên kết',
    '二合一半固定层板': 'Đợt Cam',
    '螺钉通孔二合一固定层板': 'Đợt lk vít',
    '左侧板': 'Hồi Trái',
    '右侧板': 'Hồi Phải',
    '空白中立板': 'Hồi không lk',
    '普通抽屉前板': 'Ngăn kéo trước',
    '中立板': 'Hồi Giữa',
    '后板': 'Ngăn kéo sau',
    '普通抽屉后板': 'Ngăn kéo sau',
    '左侧帮': 'Ngăn kéo trái',
    '普通抽屉左侧帮': 'Ngăn kéo trái',
    '右侧帮': 'Ngăn kéo phải',
    '普通抽屉右侧帮': 'Ngăn kéo phải',
    '普通抽屉抽屉底板': 'Đáy ngăn kéo',
    '衣通管杆': 'Suốt áo',
    '衣通两端支撑件': 'Bát treo suốt',
    '半盖式': 'BL 1/2',
    '内嵌式': 'BL 0',
    '格架横板': 'Rượu dọc',
    '格架竖板': 'Rượu ngang',
    '面板': 'Mặt ngăn kéo',
    '普通抽屉吸塑面板': 'Mặt ngăn kéo',
    '背板': 'Tấm Hậu',
    '纵向拉条': 'Nối hậu',
    '前板': 'Cánh giả',
    '顶挡侧板': 'Kẹp phào',
    '顶挡板': 'Phào',
    '三节滑轨': 'Ray bi',
    '辅板': 'Thêm',
    '竖拉条': 'Xà đứng',
    '平拉条': 'Xà ngang',
    'Cua': 'Cánh cửa',
    '门板': 'Cánh cửa',
    '铰链': 'Bản lề',
    '三合一连接件': 'Lỗ cam',
    '圆木榫': 'Chốt gỗ',
    '拉手': 'Tay nắm',
    '滑轨': 'Ray bi',
    '全盖式': 'BL 1',
    '裤架': 'Gía treo quần',
    '镀镍': 'Mạ niken',
    '木质': 'Gỗ',
    '底板': 'Tấm Đáy',
    '厚1|薄0': 'Dày 1/Mỏng0',
    '三薄一厚': 'Ba mỏng - 1 dày',
    '否': 'Không',
    '是': 'Có',
    '二长': '2 dài',
    '一长二短': '1 dài và 2 ngắn',
    '四边': '4 cạnh',
    '无': '0',
    '二短': '2 ngắn',
    '二长一短': '2 dài 1 ngắn',
    '一长一短': '1 dài 1 ngắn',
    '一长': '1 dài',
    '一短': '1 ngắn',
    '孔塞': 'Chốt đợt di động',
    '用户自定义安装样式': 'Theo chỉ định',
    '木质': 'Gỗ',
    '镀镍': 'Mạ niken',
    '底板': ' TẤM ĐÁY',
    '顶板': ' TẤM ĐỈNH',
    '踢脚板': ' CHÂN',
    '踢脚加固条': ' CHÂN PHỤ',
    '三合一固定层板': ' ĐỢT NGANG',
    '活动层板': ' ĐỢT DI ĐỘNG',
    '空白层板': ' ĐỢT KHÔNG LIÊN KẾT',
    '二合一半固定层板': ' ĐỢT CAM',
    '螺钉通孔二合一固定层板': ' ĐỢT LK VÍT',
    '左侧板': ' HỒI TRÁI',
    '右侧板': ' HỒI PHẢI',
    '空白中立板': ' HỒI KHÔNG LK',
    '普通抽屉前板': ' NGĂN KÉO TRƯỚC',
    '中立板': ' HỒI GIỮA',
    '后板': ' NGĂN KÉO SAU',
    '普通抽屉后板': ' NGĂN KÉO SAU',
    '左侧帮': ' NGĂN KÉO TRÁI',
    '普通抽屉左侧帮': ' NGĂN KÉO TRÁI',
    '右侧帮': ' NGĂN KÉO PHẢI',
    '普通抽屉右侧帮': ' NGĂN KÉO PHẢI',
    '普通抽屉抽屉底板': ' ĐÁY NGĂN KÉO',
    '衣通管杆': ' SUỐT ÁO',
    '衣通两端支撑件': ' BÁT TREO SUỐT',
    '半盖式': ' BẢN LỀ PHỦ 1/2',
    '内嵌式': ' BẢN LỀ LỌT TRONG',
    '格架横板': ' RĂNG LƯỢC DỌC',
    '格架竖板': ' RĂNG LƯỢC NGANG',
    '面板': ' MẶT NGĂN KÉO',
    '普通抽屉吸塑面板': ' MẶT NGĂN KÉO',
    '背板': ' TẤM HẬU',
    '纵向拉条': ' NỐI HẬU',
    '前板': ' CÁNH GIẢ',
    '顶挡侧板': ' KẸP PHÀO',
    '顶挡板': ' PHÀO',
    '三节滑轨': ' RAY BI',
    '辅板': ' THÊM',
    '竖拉条': ' THANH GIẰNG',
    '平拉条': ' XÀ NGANG',
    'Cua': ' TẤM CÁNH',
    '门板': ' TẤM CÁNH',
    '铰链': ' BẢN LỀ',
    '三合一连接件': ' LỖ CAM',
    '圆木榫': ' CHỐT GỖ',
    '拉手': ' TAY NẮM',
    '滑轨': ' RAY BI',
    '全盖式': ' BẢN LỀ PHỦ CẢ',
    '裤架': ' GÍA TREO QUẦN',
    '镀镍': ' MẠ NIKEN',
    '木质': ' GỖ',
    '底板': ' TẤM ĐÁY',
    '厚1|薄0': ' DÀY 1/MỎNG0',
    '三薄一厚': ' BA MỎNG - 1 DÀY',
    '否': ' KHÔNG',
    '是': ' CÓ',
    '二长': ' 2 DÀI',
    '一长二短': ' 1 DÀI VÀ 2 NGẮN',
    '四边': ' 4 CẠNH',
    '二短': ' 2 NGẮN',
    '二长一短': ' 2 DÀI 1 NGẮN',
    '一长一短': ' 1 DÀI 1 NGẮN',
    '一长': ' 1 DÀI',
    '一短': ' 1 NGẮN',
    '孔塞': ' CHỐT ĐỢT DI ĐỘNG',
    '用户自定义安装样式': ' THEO CHỈ ĐỊNH',
    '木质': ' GỖ',
    '镀镍': ' MẠ NIKEN',
    '请输入提取码': ' TÊN PHỤ KIỆN',
    '规格': ' THÔNG SỐ KT',
    '五金件清单': ' DANH SÁCH PHỤ KIỆN',
    '数量': ' SỐ LƯỢNG',
    '备注': ' GHI CHÚ',
    '单价': ' ĐƠN GIÁ',
    '总价': ' THÀNH TIỀN',
    '总额': ' TỔNG SỐ TIỀN',
    '五金件名称': ' TÊN PHỤ KIỆN',
    '滑轨 ': ' RAY BI 3 TẦNG',
    '普通抽屉': ' THÙNG NGĂN KÉO',
    'VGT': ' VAI GIƯỜNG TRÁI NẸP 44',
    'VGP': ' VAI GIƯỜNG PHẢI NẸP 44',
    'DGG': ' ĐẦU GIƯỜNG NẸP 44',
    'DG': ' ĐUÔI GIƯỜNG NẸP 44',
    'GG': ' GIÁT GIƯỜNG',
    'TG': ' THANG GIƯỜNG',
    'HTKL': ' HỒI TRÁI KẸP LỢI NẸP 44',
    'HPKL': ' HỒI PHẢI KẸP LỢI NẸP 44',
    'DKL': ' ĐỈNH KẸP LỢI NẸP 44',
    'HGKL': ' HỒI GIỮA KẸP LỢI NẸP 44',
    'KL': ' KẸP LỢI NẸP 44',
    'CM': 'CHÉM MÒI',
    'KLD': ' ĐÁY KẸP LỢI NẸP 44',
    'NVG': ' NẸP VÂN GỖ',
    '横向拉条': 'SẬP XẺ ĐÔI 45 ĐỘ',
    'YXHồiphải': 'HỒI PHẢI',
    'YXHồitrái': 'HỒI TRÁI',
    'Hồitrái': 'HỒI TRÁI',
    'PhổthôngTấmhậu': 'THÀNH NK SAU',
    'Dảikéodài': 'THANH GIẰNG',
    'PhổthôngHộcNK-Trước': 'THÀNH NK TRƯỚC',
    'PhổthôngHộcNK-Phải': 'THÀNH NK PHẢI',
    'PhổthôngHộcNK-Trái': 'THÀNH NK TRÁI',
    'YXHồitrong': 'HỒI GIỮA',
    'Hồitrong': 'HỒI GIỮA',
    'YXTấmđáy': 'TẤM ĐÁY',
    'Hồiphải': 'HỒI PHẢI',
    'YXChân': 'TẤM ĐỈNH',
    'Tấmđợt': 'TẤM ĐỢT',
    'Tấmtrước': 'TẤM FIX',
    'Giằngdọc': 'THANH GIẰNG',
    'YXTấmđợt': 'TẤM ĐỢT',
    'PhổthôngTấmdánphủmặtTấmmặt': 'MẶT NGĂN KÉO',
    'Tựnhiên': 'TRÁN TỦ',
    'Chântủ': 'CHÂN TỦ',
    'Thanhgiacường': 'CHÂN TỦ',
    'Tấmhậu': 'TẤM HẬU',
    'PhổthôngTấmđáy': 'ĐÁY NGĂN KÉO',
    'Tấmcánh': 'TẤM CÁNH',
    'Tấmngang': 'PHÀO TRÁN TỦ',
    'Phổ thôngThường gặpTấm mặt': 'MẶT NGĂN KÉO',
    'Chân': 'TẤM ĐỈNH',
    'Tấmđáy': 'TẤM ĐÁY',
    'YXTấmhậu': 'TẤM HẬU',
    'TT': 'THANH TREO CHÉM MÒI',
    'YXVGT': ' VAI GIƯỜNG TRÁI NẸP 44',
    'YXVGP': ' VAI GIƯỜNG PHẢI NẸP 44',
    'YXDGG': ' ĐẦU GIƯỜNG NẸP 44',
    'YXDG': ' ĐUÔI GIƯỜNG NẸP 44',
    'YXGG': ' GIÁT GIƯỜNG',
    'YXTG': ' THANG GIƯỜNG',
    'YXHTKL': ' HỒI TRÁI KẸP LỢI NẸP 44',
    'YXHPKL': ' HỒI PHẢI KẸP LỢI NẸP 44',
    'YXDKL': ' ĐỈNH KẸP LỢI NẸP 44',
    'YXHGKL': ' HỒI GIỮA KẸP LỢI NẸP 44',
    'YXKL': ' KẸP LỢI NẸP 44',
    'YXCM': 'CHÉM MÒI',
    'YXKLD': ' ĐÁY KẸP LỢI NẸP 44',
    'YXNVG': ' NẸP VÂN GỖ',
    'YX三合一固定层板': 'ĐỢT NGANG',
    'YX三合一固定层板': 'ĐỢT NGANG',
    'YX三合一固定层板': ' ĐỢT NGANG',
    'YX三合一固定层板': ' ĐỢT NGANG',
    'YX三合一固定层板': ' ĐỢT NGANG',
    'YX三合一固定层板': ' ĐỢT NGANG',
    'YX顶板': ' TẤM ĐỈNH',
    'YX左侧板': ' HỒI TRÁI',
    'YX右侧板': ' HỒI PHẢI',
    'YX中立板': ' HỒI GIỮA',
    'YX底板': ' TẤM ĐÁY',
    'Giằngngang': 'THANH GIẰNG',
    'YXTấmcánh': 'TẤM CÁNH',
    'YX门板': 'TẤM CÁNH',
    'Đợtkhônglỗ': 'TẤM ĐỢT',
    'YXĐợtkhônglỗ': 'TẤM ĐỢT',
    'Tấmcánh': 'TẤM CÁNH',
    'YXTấmcánh': 'TẤM CÁNH',
    'Tấmcạnhđứng': 'PHÀO HỒI',
    'Hồitrongkhônglỗ': 'HỒI GIỮA',
    'Chântủ': 'CHÂN TỦ',
    'Thanhgiacường': 'CHÂN TỦ',
    'YXTấmđợt': 'TẤM ĐỢT',
    'Tấmôdọc': 'HỒI GIỮA',
    'Tấmôdọc': 'HỒI GIỮA',
    'Tấmtrước': 'TẤM FIX',
    'Hồiphải': 'HỒI PHẢI',
    'Hồitrái': 'HỒI TRÁI',
    'Tấmđáy': 'TẤM ĐÁY',
    'DKL': 'ĐỈNH KẸP LỢI NẸP 44',
    'Hồitrái': 'HỒI TRÁI',
    'Tấmngangôvuông': 'THANH LỒNG NGANG',
    'Tấmôdọc': 'THANH LỒNG DỌC',
    'Tấmngangôvuông': 'THANH LỒNG NGANG',
    'Tấmôdọc': 'THANH LỒNG DỌC',
    'YXTựnhiên': 'TRÁN TỦ',
    'YXTấmtrước': 'TẤM FIX',
    'YXTựnhiên': 'TRÁN TỦ',
    'YXTấmtrước': 'TẤM FIX',
    'KL': ' KẸP LỢI NẸP 44',
    'YXKL': ' KẸP LỢI NẸP 44',
    'Tấmđợt': 'TẤM ĐỢT',
    'YXHồiphải': 'HỒI PHẢI',
    'YXHồitrái': 'HỒI TRÁI',
    'Hồitrong': 'HỒI GIỮA',
    'Tựnhiên': 'TRÁN TỦ',
    'Giằngdọc': 'THANH GIẰNG',
    'PhổthôngTấmhậu': 'THÀNH NK SAU',
    'PhổthôngTấmdánphủmặtTấmmặt': 'MẶT NGĂN KÉO',
    'YXPhổthôngHộcNK-Trước': 'THÀNH NK TRƯỚC',
    'YXPhổthôngTấmhậu': 'THÀNH NK SAU',
    'Chân': 'TẤM ĐỈNH',
    'Hồiphải': 'HỒI PHẢI',
    'Tấmhậu': 'TẤM HẬU',
    'Tấmmặt': 'MẶT NGĂN KÉO',
    'PhổthôngHộcNK-Trái': 'THÀNH NK TRÁI',
    'PhổthôngHộcNK-Trước': 'THÀNH NK TRƯỚC',
    'PhổthôngTấmđáy': 'ĐÁY NGĂN KÉO',
    'PhổthôngHộcNK-Phải': 'THÀNH NK PHẢI',
    'PhổthôngTấmhậu': 'THÀNH NK SAU',
    'Tấmngang': 'PHÀO TRÁN TỦ',
    'Tấmcạnhđứng': 'TRÁN TỦ',
    'Tấmngang': 'PHÀO TRÁN TỦ',
    'Tấmmặt': 'MẶT NGĂN KÉO',
    'Tấmmặt': 'MẶT NGĂN KÉO',
    'YXTấmhậu': 'TẤM HẬU',
    'TT': 'THANH TREO CHÉM MÒI',
    'YXVGT': ' VAI GIƯỜNG TRÁI NẸP 44',
    'YXVGP': ' VAI GIƯỜNG PHẢI NẸP 44',
    'YXDGG': ' ĐẦU GIƯỜNG NẸP 44',
    'YXDG': ' ĐUÔI GIƯỜNG NẸP 44',
    'YXGG': ' GIÁT GIƯỜNG',
    'YXTG': ' THANG GIƯỜNG',
    'YXHTKL': ' HỒI TRÁI KẸP LỢI NẸP 44',
    'YXHPKL': ' HỒI PHẢI KẸP LỢI NẸP 44',
    'YXDKL': ' ĐỈNH KẸP LỢI NẸP 44',
    'YXHGKL': ' HỒI GIỮA KẸP LỢI NẸP 44',
    'YXKL': ' KẸP LỢI NẸP 44',
    'YXCM': 'CHÉM MÒI',
    'YXKLD': ' ĐÁY KẸP LỢI NẸP 44',
    'YXNVG': ' NẸP VÂN GỖ',
    'YX三合一固定层板': 'ĐỢT NGANG',
    'YX三合一固定层板': 'ĐỢT NGANG',
    'YX三合一固定层板': ' ĐỢT NGANG',
    'YX三合一固定层板': ' ĐỢT NGANG',
    'YX三合一固定层板': ' ĐỢT NGANG',
    'YX三合一固定层板': ' ĐỢT NGANG',
    'YX顶板': ' TẤM ĐỈNH',
    'YX左侧板': ' HỒI TRÁI',
    'YX右侧板': ' HỒI PHẢI',
    'YX中立板': ' HỒI GIỮA',
    'YX底板': ' TẤM ĐÁY',
    'Giằngngang': 'THANH GIẰNG',
    'YXTấmcánh': 'TẤM CÁNH',
    'YX门板': 'TẤM CÁNH',
    'Đợtkhônglỗ': 'TẤM ĐỢT',
    'YXĐợtkhônglỗ': 'TẤM ĐỢT',
    '底板': ' TẤM ĐÁY',
    '顶板': ' TẤM ĐỈNH',
    '踢脚板': ' CHÂN',
    '踢脚加固条': ' CHÂN PHỤ',
    '三合一固定层板': ' ĐỢT NGANG',
    '活动层板': ' ĐỢT DI ĐỘNG',
    '空白层板': ' ĐỢT KHÔNG LIÊN KẾT',
    '二合一半固定层板': ' ĐỢT CAM',
    '螺钉通孔二合一固定层板': ' ĐỢT LK VÍT',
    '左侧板': ' HỒI TRÁI',
    '右侧板': ' HỒI PHẢI',
    '空白中立板': ' HỒI KHÔNG LK',
    '普通抽屉前板': ' NGĂN KÉO TRƯỚC',
    '中立板': ' HỒI GIỮA',
    '后板': ' NGĂN KÉO SAU',
    '普通抽屉后板': ' NGĂN KÉO SAU',
    '左侧帮': ' NGĂN KÉO TRÁI',
    '普通抽屉左侧帮': ' NGĂN KÉO TRÁI',
    '右侧帮': ' NGĂN KÉO PHẢI',
    '普通抽屉右侧帮': ' NGĂN KÉO PHẢI',
    '普通抽屉抽屉底板': ' ĐÁY NGĂN KÉO',
    '衣通管杆': ' SUỐT ÁO',
    '衣通两端支撑件': ' BÁT TREO SUỐT',
    '半盖式': ' BẢN LỀ PHỦ 1/2',
    '内嵌式': ' BẢN LỀ LỌT TRONG',
    '格架横板': ' RĂNG LƯỢC DỌC',
    '格架竖板': ' RĂNG LƯỢC NGANG',
    '面板': ' MẶT NGĂN KÉO',
    '普通抽屉吸塑面板': ' MẶT NGĂN KÉO',
    '背板': ' TẤM HẬU',
    '纵向拉条': ' NỐI HẬU',
    '前板': ' CÁNH GIẢ',
    '顶挡侧板': ' KẸP PHÀO',
    '顶挡板': ' PHÀO',
    '三节滑轨': ' RAY BI',
    '辅板': ' THÊM',
    '竖拉条': ' THANH GIẰNG',
    '平拉条': ' XÀ NGANG',
    'Cua': ' TẤM CÁNH',
    '门板': ' TẤM CÁNH',
    '铰链': ' BẢN LỀ',
    '三合一连接件': ' LỖ CAM',
    '圆木榫': ' CHỐT GỖ',
    '拉手': ' TAY NẮM',
    '滑轨': ' RAY BI',
    '全盖式': ' BẢN LỀ PHỦ CẢ',
    '裤架': ' GÍA TREO QUẦN',
    '镀镍': ' MẠ NIKEN',
    '木质': ' GỖ',
    '底板': ' TẤM ĐÁY',
    '厚1|薄0': ' DÀY 1/MỎNG0',
    '三薄一厚': ' BA MỎNG - 1 DÀY',
    '否': ' KHÔNG',
    '是': ' CÓ',
    '二长': ' 2 DÀI',
    '一长二短': ' 1 DÀI VÀ 2 NGẮN',
    '四边': ' 4 CẠNH',
    '二短': ' 2 NGẮN',
    '二长一短': ' 2 DÀI 1 NGẮN',
    '一长一短': ' 1 DÀI 1 NGẮN',
    '一长': ' 1 DÀI',
    '一短': ' 1 NGẮN',
    '孔塞': ' CHỐT ĐỢT DI ĐỘNG',
    '用户自定义安装样式': ' THEO CHỈ ĐỊNH',
    '木质': ' GỖ',
    '镀镍': ' MẠ NIKEN',
    '请输入提取码': ' TÊN PHỤ KIỆN',
    '规格': ' THÔNG SỐ KT',
    '五金件清单': ' DANH SÁCH PHỤ KIỆN',
    '数量': ' SỐ LƯỢNG',
    '备注': ' GHI CHÚ',
    '单价': ' ĐƠN GIÁ',
    '总价': ' THÀNH TIỀN',
    '总额': ' TỔNG SỐ TIỀN',
    '五金件名称': ' TÊN PHỤ KIỆN',
    '滑轨 ': ' RAY BI 3 TẦNG',
    '普通抽屉': ' THÙNG NGĂN KÉO',
    'VGT': ' VAI GIƯỜNG TRÁI NẸP 44',
    'VGP': ' VAI GIƯỜNG PHẢI NẸP 44',
    'DGG': ' ĐẦU GIƯỜNG NẸP 44',
    'DG': ' ĐUÔI GIƯỜNG NẸP 44',
    'GG': ' GIÁT GIƯỜNG',
    'TG': ' THANG GIƯỜNG',
    'HTKL': ' HỒI TRÁI KẸP LỢI NẸP 44',
    'HPKL': ' HỒI PHẢI KẸP LỢI NẸP 44',
    'DKL': ' ĐỈNH KẸP LỢI NẸP 44',
    'HGKL': ' HỒI GIỮA KẸP LỢI NẸP 44',
    'KL': ' KẸP LỢI NẸP 44',
    'CM': 'CHÉM MÒI',
    'KLD': ' ĐÁY KẸP LỢI NẸP 44',
    'NVG': ' NẸP VÂN GỖ',
    '横向拉条': 'SẬP XẺ ĐÔI 45 ĐỘ',
    'YXHồitrongkhônglỗ': 'HỒI GIỮA',
}